// Generated by https://quicktype.io

import { Participant } from "./participant";
import { Request } from "./request";

export interface Transaction {
  id: number;
  type: string;
  typeVarchar: string;
  month: number;
  year: number;
  points: number;
  description: null | string;
  beforePoints: number;
  afterPoints: number;
  isPending: boolean;
  isDeleted: boolean;
  deletedAt: null;
  participant: Participant;
  request: Request | null;
  rollbackTransaction: null;
  sourceRollbackTransaction: null;
  dishItem: DishItem | null;
  transactionSnaps: any[];
  transactionParticipants: any[];
  transactionResults: any[];
  transactionJobsProfiles: any[];
}

export interface DishItem {
  id: number;
  order: number;
  hierarchy: string;
  isDeleted: boolean;
  deletedAt: null;
  dish: Dish;
  ingredient: Ingredient;
}

export interface Dish {
  id: number;
  order: number;
  name: string;
  description: null;
  hierarchy: string;
  isDeleted: boolean;
  deletedAt: null;
}

export interface Ingredient {
  id: number;
  code: string;
  codeVarchar: null;
  name: string;
  description: string;
  isDeleted: boolean;
  deletedAt: null;
}
